env:
  seed: 10
  param:
    durations: 750
    scenario: "ecr"
    topology: 'global_trade.22p_l0.0'
    # topology: "toy.4p_ssdd_l0.0"
training:
  enable: True
  parallel_cnt: 24
  device: 'cuda:1'
  batch_size: 1024
  shuffle_time: 1
  rollout_cnt: 1000
  train_freq: 1
  model_save_freq: 1
  gamma: 0.99
  learning_rate: 0.00005
  td_steps: 100
  entropy_loss_enable: True
model:
  # path: '/data/log/20200119/demo_6p'
  path: '/dcdata/log/test'
  path: none
  tick_buffer: 20
  hidden_size: 32
  graph_output_dim: 32
  action_dim: 21
  feature:
    attention_order: temporal # meta_path_cnt, temporal or random
    onehot_identity: False
log:
  path: /dcdata/log/
  # be careful to turn this on
  snapshot: True
  exp:
    enable: false
    freq: 10
